# Generated by Django 4.2.20 on 2025-05-04 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='passwort',
            new_name='password',
        ),
    ]
