# Generated by Django 4.2.21 on 2025-05-10 11:00

import TastyRecipesApp.profiles.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('first_name', models.CharField(max_length=30, validators=[TastyRecipesApp.profiles.validators.CapitalLetterValidator()])),
                ('last_name', models.CharField(max_length=30, validators=[TastyRecipesApp.profiles.validators.CapitalLetterValidator()])),
                ('chef', models.BooleanField(default=False)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
